apiVersion: v1
kind: Secret
metadata:
  name: {{ template "beer-service-web.fullname" . }}
  labels:
    app: {{ template "beer-service-web.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  springDatasourceUrl: {{ .Values.beerService.deployment.springDatasourceUrl | b64enc | quote }}
